CREATE TABLE IF NOT EXISTS "public"."endpoint" (
  "id" bigserial NOT NULL,
  "fhir_id" text NOT NULL,
  "resource_type" text,
  "language" text,
  "text_status" text,
  "text_div" text,
  "status" text,
  "connection_type_system" text,
  "connection_type_code" text,
  "name" text,
  "address" text,
  "connection_type_version" text,
  "connection_type_display" text,
  "managing_organization_display" text,
  "endpoint_environment_type" text,
  "endpointAccessControlMechanism" text,
  "associatedServers" text,
  "secureExchangeArtifacts" text,
  "trustFramework" text,
  "verification_status" text,
  "specific_connection_type" text,
  "identifier_status" text,
  "coding_system" text,
  "coding_version" text,
  "coding_code" text,
  "coding_display" text,
  "identifier_system" text,
  "identifier_value" text,
  CONSTRAINT "endpoint_pk" PRIMARY KEY ("id"),
  CONSTRAINT "endpoint_fhir_id_uniq" UNIQUE NULLS NOT DISTINCT ("fhir_id")
);
CREATE INDEX IF NOT EXISTS "endpoint_fhir_id_idx" ON "public"."endpoint" ("fhir_id");
