CREATE TABLE IF NOT EXISTS "public"."location" (
  "id" bigserial NOT NULL,
  "fhir_id" text NOT NULL,
  "resource_type" text,
  "language" text,
  "text_status" text,
  "text_div" text,
  "status" text,
  "name" text,
  "address_state" text,
  "address_city" text,
  "address_postal_code" text,
  "position_longitude" numeric,
  "position_latitude" numeric,
  "description" text,
  "address_use" text,
  "address_type" text,
  "address_text" text,
  "address_country" text,
  "managing_organization_display" text,
  "availability_exceptions" text,
  "managing_organization_id" bigint,
  "verification_status" text,
  "newpatients_characteristics" text,
  "type_text" text,
  "coding_system" text,
  "coding_code" text,
  "coding_display" text,
  "identifier_use" text,
  "identifier_system" text,
  "identifier_value" text,
  "identifier_assigner_reference" text,
  "identifier_assigner_display" text,
  CONSTRAINT "location_pk" PRIMARY KEY ("id"),
  CONSTRAINT "location_fhir_id_uniq" UNIQUE NULLS NOT DISTINCT ("fhir_id")
);
CREATE INDEX IF NOT EXISTS "location_fhir_id_idx" ON "public"."location" ("fhir_id");
CREATE INDEX IF NOT EXISTS "location_managing_organization_id_idx" ON "public"."location" ("managing_organization_id");
