CREATE TABLE IF NOT EXISTS "public"."organization_prvgrp" (
  "id" bigserial NOT NULL,
  "fhir_id" text NOT NULL,
  "resource_type" text,
  "language" text,
  "text_status" text,
  "text_div" text,
  "active" boolean,
  "name" text,
  "identifier_status" text,
  "verification_status" text,
  "identifier_system" text,
  "identifier_value" text,
  "identifier_use" text,
  "identifier_assigner_display" text,
  "type_text" text,
  "coding_system" text,
  "coding_code" text,
  "coding_display" text,
  "contact_name_use" text,
  "contact_name_text" text,
  "contact_name_family" text,
  "contact_address_use" text,
  "contact_address_type" text,
  "contact_address_text" text,
  "contact_address_city" text,
  "contact_address_state" text,
  "contact_address_postal_code" text,
  "contact_address_country" text,
  "telecom_system" text,
  "telecom_value" text,
  "telecom_rank" integer,
  "telecom_use" text,
  "coding_system" text,
  "coding_code" text,
  "coding_display" text,
  CONSTRAINT "organization_prvgrp_pk" PRIMARY KEY ("id"),
  CONSTRAINT "organization_prvgrp_fhir_id_uniq" UNIQUE NULLS NOT DISTINCT ("fhir_id")
);
CREATE INDEX IF NOT EXISTS "organization_prvgrp_fhir_id_idx" ON "public"."organization_prvgrp" ("fhir_id");
