CREATE TABLE IF NOT EXISTS "public"."organization_cg" (
  "id" bigserial NOT NULL,
  "fhir_id" text NOT NULL,
  "resource_type" text,
  "text_status" text,
  "text_div" text,
  "active" boolean,
  "name" text,
  "verification_status" text,
  "identifier_status" text,
  "identifier_use" text,
  "identifier_system" text,
  "identifier_value" text,
  "type_text" text,
  "coding_system" text,
  "coding_version" text,
  "coding_code" text,
  "coding_display" text,
  "address_use" text,
  "address_type" text,
  "address_text" text,
  "address_city" text,
  "address_state" text,
  "address_postal_code" text,
  "address_country" text,
  "contact_address_use" text,
  "contact_address_type" text,
  "contact_address_text" text,
  "contact_address_city" text,
  "contact_address_state" text,
  "contact_address_postal_code" text,
  "contact_address_country" text,
  "telecom_system" text,
  "telecom_value" text,
  "telecom_use" text,
  CONSTRAINT "organization_cg_pk" PRIMARY KEY ("id"),
  CONSTRAINT "organization_cg_fhir_id_uniq" UNIQUE NULLS NOT DISTINCT ("fhir_id")
);
CREATE INDEX IF NOT EXISTS "organization_cg_fhir_id_idx" ON "public"."organization_cg" ("fhir_id");
