CREATE TABLE IF NOT EXISTS "public"."organization_govt" (
  "id" bigserial NOT NULL,
  "fhir_id" text NOT NULL,
  "resource_type" text,
  "text_status" text,
  "text_div" text,
  "active" boolean,
  "name" text,
  "language" text,
  "verification_status" text,
  "identifier_status" text,
  "identifier_system" text,
  "identifier_value" text,
  "type_text" text,
  "coding_system" text,
  "coding_version" text,
  "coding_code" text,
  "coding_display" text,
  "telecom_system" text,
  "telecom_value" text,
  "telecom_use" text,
  CONSTRAINT "organization_govt_pk" PRIMARY KEY ("id"),
  CONSTRAINT "organization_govt_fhir_id_uniq" UNIQUE NULLS NOT DISTINCT ("fhir_id")
);
CREATE INDEX IF NOT EXISTS "organization_govt_fhir_id_idx" ON "public"."organization_govt" ("fhir_id");
